### ISSUE TITLE
Change the extension metadata name to "Bedtime Mode"

### ISSUE THREAD

**Issue by wbolster** [ionutbortis/gnome-bedtime-mode#6]
this extension currently shows as ‘gnome bedtime’ in the extensions ui. since the list is alphabetically sorted, this makes it hard to find. can you rename it to just ‘bedtime’?

**Comment by ionutbortis** [comment]
I think it's not that easy to fully rename an extension. Maybe the current name is not that inspired, probably "Bedtime Mode" would have been a better choice. 

If it were to be renamed, my ocd will not let me rest until I fully do it. This means also changing the extension's uuid to something like "bedtimemode@ionutbortis.gmail.com", settings-schema, github url, and so on. 
By changing the uuid the future submissions to the extensions website will probably create a new extension on the website and the existing users will need to migrate to the newer entry which is the same except the name and some ids. 

I believe it's best to keep the current naming conventions in order to avoid confusion and to preserve the existing users of the extension.

Another thing to keep in mind is that maybe the Extensions app needs better handling of the extensions list display. Maybe it should offer the possibility of filtering for a specific text. 
I see that the Tweaks app, which includes an Extensions section on the left side, provides a search functionality. 

To rename an extension just to pop earlier on a list displayed by another app might not be the best approach...

**Comment by wbolster** [comment]
i don't think any of the follow-up changes you mentioned are justified.

yes, this is "gnome bedtime", but once you're inside gnome i expect it to show up as "bedtime". literally no other extension or if the 20 or so on my system use the "gnome" prefix, because, well, it's just redundant. that's what this issue is about. keep it simple and pragmatic 🙃

**Comment by wbolster** [comment]
(also it's not "another app"; it's the official gnome interface to manage extensions)

**Comment by ionutbortis** [comment]
I would still like to preserve naming consistency but I guess renaming just the name is not that bad. My ocd doesnt't agree but I'll let it slide for now.

I will change just the name to "Bedtime Mode" and keep the rest as it is.
