### ISSUE TITLE
Provide different color schemes for the Bedtime Mode effect

### ISSUE THREAD

**Issue by wbolster** [ionutbortis/gnome-bedtime-mode#7]
hi, thanks for this extension! i stumbled upon this one while looking for a replacement for https://github.com/amarovita/tint-all which is not really maintained and no longer works with gnome 40.

i would love to see a ’sepia style’ in addition to the plain grayscale. i find it easier on the eyes, and it would make this extension quite useful as a ‘low stimulus’ mode.

**Comment by ionutbortis** [comment]
Hello,

Thank you for using the extension and suggesting new features!

Unfortunately, at the moment the extension is in low maintenance mode since I switched focus to some other projects. 
I originally thought of adding different color choices for the active bedtime mode but on a second thought I felt its best to keep it as simple as possible.

I believe the main focus of the extension is to signal that you should try to restrict yourself in using your device when the Bedtime Mode is on. This means that if the experience of using the gnome desktop under a grayscale filter is not that pleasant, then the extension is actually working as expected :)

Making the Bedtime Mode more pleasant by using different color schemes or lesser effect factors, kinda defeats its purpose, isn't it?

I also thought of adding a setting for a "strict mode" that will make it harder for the user to disable the grayscale effect. I believe the best results are when you stop using your device when the bedtime mode turns on. 

The extension is useful if you still want to have your device on for listening music, audio books or podcasts, but you don't sit in front of it anymore. Otherwise, you can just power off your device :)

If there are other people requesting different color schemes maybe I'll reconsider this and make it a higher priority. 
For the moment I'll leave it here but with a lower priority.

Thanks!

**Comment by hex007** [comment]
I am currently using it to reduce saturation on my laptop during work hours. Helps to a great extent when the screen is too good.

I am using a factor of 0.5 on the factor calculation based on timestep so the de-saturation only reaches 0 - 0.5 rather than 0 - 1. 

A simple handle to change minimum saturation reached would be helpful.

**Comment by ionutbortis** [comment]
Hello,

Thanks for the feedback and feature proposal!
I will try to add some functionality on the color/factor change for the next release.

I'm thinking on two options:
- Predefined list with alternate overlay colors. Something similar to tint-all extension.
- Some kind of color picker or color code input. 

There will also be some kind of slider/spinner in order to set the maximum effect level (10 - 100%).

**Comment by ionutbortis** [comment]
@wbolster @hex007
Hi guys,  

If you're still using Gnome :sweat_smile:, you might want to check the latest version of this extension. All the feature requests were implemented :tada: 

[Here](https://github.com/ionutbortis/gnome-bedtime-mode/releases/tag/v5.0) you can find more details of the latest changes.
Note: Use the [latest version (6)](https://github.com/ionutbortis/gnome-bedtime-mode/releases/tag/v6.0) because 5 has some weird ui crash issue on gnome 3.38. The crash issue was fixed on version 6.

**Comment by wbolster** [comment]
awesome, will give it a spin soon 🤩

and yes, of course i still use it. 20+ yrs non stop gnome user here 👍

**Comment by wbolster** [comment]
the sepia one is awesome, thanks!

it would be great if changing the intensity was made simpler, e.g. scrollwheel on the top bar icon.

**Comment by ionutbortis** [comment]
Hmm, that'l should be possible.

I guess I will need to add a setting to enable this, which will be off by default.

Can you please open an enhancement for this? Thanks!

**Comment by hex007** [comment]
I will try this out today. Thanks for getting back to it
